### ISSUE TITLE
local functions in syngrid vm mode

### ISSUE THREAD

**Issue by eranschweitzer** [MATPOWER/matpower-extras#3]
commit 5ea826d1f260a1a4eef59f1b3fda814f0aad5f27 changed the way local functions are handled in the `sgvm_GenerationClass` (and possibly in `sgvm_IndClass`). These are now "private" functions denoted with a leading `_`.
For example, the `evolve_children` function became `_evolve_children`.
Apparently this was done for Octave compatibility, however, it appears that Matlab does not allow for functions to be led with `_`.

Possible solutions:
1. simply remove the leading underscore or replace with a different prefix.
2. switch to private methods as done in Matlab: https://www.mathworks.com/help/matlab/matlab_oop/method-attributes.html. (is this supported by Octave?)
3. turn these into standalone functions (i.e. separate `.m` file) 

Thoughts?

**Comment by rdzman** [comment]
I was about to say that I think there must be something "special" about your MATLAB, since I ran the `t_syngrid_vm` test successfully on R2016b, R2017b and R2018b on my machine.

Then I discovered that the paths I was using for testing were pointing to my pre-GitHub version of the syngrid repo. So I was testing locally (MATLAB and Octave 4.4) against the original local functions, which worked fine. But the Octave 4.2 (used by the Travis-CI testing), which failed on that version, hence the modifications, was being tested against the modified GitHub version.

So, yes, I think solution 1 is the simplest. I'll just remove the leading underscore.

Thanks for catching this.

**Comment by rdzman** [comment]
Btw, I just noticed that this was in the [issue tracker for MATPOWER Extras](https://github.com/MATPOWER/matpower-extras/issues).

For future reference, SynGrid is a sub-repository in [MATPOWER Extras](https://github.com/MATPOWER/matpower-extras), with its own master repository at [mx-syngrid](https://github.com/MATPOWER/mx-syngrid) and it's own [issue tracker](https://github.com/MATPOWER/mx-syngrid/issues) where SynGrid issues and pull requests should be handled.
